"""empty message

Revision ID: 56d767d44ed7
Revises: cc05bc5dd37c
Create Date: 2024-03-18 21:37:42.514865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d767d44ed7'
down_revision = 'cc05bc5dd37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
