"""empty message

Revision ID: cc05bc5dd37c
Revises: 
Create Date: 2024-03-18 21:34:22.121435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc05bc5dd37c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_date')

    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
